/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    "match-v4.MatchFrameDto": {
      participantFrames: { [key: string]: ref };
      events: components["schemas"]["match-v4.MatchEventDto"][];
      timestamp: number;
    };
    "match-v4.MatchParticipantFrameDto": {
      participantId: number;
      minionsKilled: number;
      teamScore?: number;
      dominionScore?: number;
      totalGold: number;
      level: number;
      xp: number;
      currentGold: number;
      position?: components["schemas"]["match-v4.MatchPositionDto"];
      jungleMinionsKilled: number;
    };
    "match-v4.MatchPositionDto": { x: number; y: number };
    "match-v4.MatchEventDto": {
      laneType?: string;
      skillSlot?: number;
      ascendedType?: string;
      creatorId?: number;
      afterId?: number;
      eventType?: string;
      /**
       * (Legal values:  CHAMPION_KILL,  WARD_PLACED,  WARD_KILL,  BUILDING_KILL,  ELITE_MONSTER_KILL,  ITEM_PURCHASED,  ITEM_SOLD,  ITEM_DESTROYED,  ITEM_UNDO,  SKILL_LEVEL_UP,  ASCENDED_EVENT,  CAPTURE_POINT,  PORO_KING_SUMMON)
       */
      type:
        | "CHAMPION_KILL"
        | "WARD_PLACED"
        | "WARD_KILL"
        | "BUILDING_KILL"
        | "ELITE_MONSTER_KILL"
        | "ITEM_PURCHASED"
        | "ITEM_SOLD"
        | "ITEM_DESTROYED"
        | "ITEM_UNDO"
        | "SKILL_LEVEL_UP"
        | "ASCENDED_EVENT"
        | "CAPTURE_POINT"
        | "PORO_KING_SUMMON";
      levelUpType?: string;
      wardType?: string;
      participantId?: number;
      towerType?: string;
      itemId?: number;
      beforeId?: number;
      pointCaptured?: string;
      monsterType?: string;
      monsterSubType?: string;
      teamId?: number;
      position?: components["schemas"]["match-v4.MatchPositionDto"];
      killerId?: number;
      timestamp: number;
      assistingParticipantIds?: number[];
      buildingType?: string;
      victimId?: number;
    };
  };
}
