///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// http://www.mingweisamuel.com/riotapi-schema/tool/
// Version 909460d67267a0122544094d93120b50f8d0f5de


/** 32-bit integer (signed). */
type int = number;
/** 64-bit integer (signed). */
type long = number;
/** 32-bit single-precision float. */
type float = number;
/** 64-bit double-precision float. */
type double = number;


namespace championMasteryV4 {
    /**
     * ChampionMasteryDTO data object, automatically generated.
     * # Description
     * This object contains single Champion Mastery information for player and champion combination.
     */
    export interface ChampionMasteryDTO {
        /** Number of points needed to achieve next level. Zero if player reached maximum champion level for this champion. */
        championPointsUntilNextLevel?: long | null;
        /** Is chest granted for this champion or not in current season. */
        chestGranted?: boolean | null;
        /** Champion ID for this entry. */
        championId?: long | null;
        /** Last time this champion was played by this player - in Unix milliseconds time format. */
        lastPlayTime?: long | null;
        /** Champion level for specified player and champion combination. */
        championLevel?: int | null;
        /** Summoner ID for this entry. (Encrypted) */
        summonerId?: string | null;
        /** Total number of champion points for this player and champion combination - they are used to determine championLevel. */
        championPoints?: int | null;
        /** Number of points earned since current level has been achieved. */
        championPointsSinceLastLevel?: long | null;
        /** The token earned for this champion to levelup. */
        tokensEarned?: int | null;
    }
}

namespace championV3 {
    /**
     * ChampionInfo data object, automatically generated.
     */
    export interface ChampionInfo {
        maxNewPlayerLevel?: int | null;
        freeChampionIdsForNewPlayers?: Array<int> | null;
        freeChampionIds?: Array<int> | null;
    }
}

namespace clashV1 {
    /**
     * PlayerDto data object, automatically generated.
     */
    export interface PlayerDto {
        summonerId?: string | null;
        teamId?: string | null;
        /** (Legal values:  UNSELECTED,  FILL,  TOP,  JUNGLE,  MIDDLE,  BOTTOM,  UTILITY) */
        position?: "UNSELECTED" | "FILL" | "TOP" | "JUNGLE" | "MIDDLE" | "BOTTOM" | "UTILITY" | null;
        /** (Legal values:  CAPTAIN,  MEMBER) */
        role?: "CAPTAIN" | "MEMBER" | null;
    }
}

namespace clashV1 {
    /**
     * TeamDto data object, automatically generated.
     */
    export interface TeamDto {
        id?: string | null;
        tournamentId?: int | null;
        name?: string | null;
        iconId?: int | null;
        tier?: int | null;
        /** Summoner ID of the team captain. */
        captain?: string | null;
        abbreviation?: string | null;
        /** Team members. */
        players?: Array<clashV1.PlayerDto> | null;
    }
}

namespace clashV1 {
    /**
     * TournamentDto data object, automatically generated.
     */
    export interface TournamentDto {
        id?: int | null;
        themeId?: int | null;
        nameKey?: string | null;
        nameKeySecondary?: string | null;
        /** Tournament phase. */
        schedule?: Array<clashV1.TournamentPhaseDto> | null;
    }
}

namespace clashV1 {
    /**
     * TournamentPhaseDto data object, automatically generated.
     */
    export interface TournamentPhaseDto {
        id?: int | null;
        registrationTime?: long | null;
        startTime?: long | null;
        cancelled?: boolean | null;
    }
}

namespace leagueExpV4 {
    /**
     * LeagueEntryDTO data object, automatically generated.
     */
    export interface LeagueEntryDTO {
        leagueId?: string | null;
        /** Player's summonerId (Encrypted) */
        summonerId?: string | null;
        summonerName?: string | null;
        queueType?: string | null;
        tier?: string | null;
        rank?: string | null;
        leaguePoints?: int | null;
        /** Winning team on Summoners Rift. First placement in Teamfight Tactics. */
        wins?: int | null;
        /** Losing team on Summoners Rift. Second through eighth placement in Teamfight Tactics. */
        losses?: int | null;
        hotStreak?: boolean | null;
        veteran?: boolean | null;
        freshBlood?: boolean | null;
        inactive?: boolean | null;
        miniSeries: leagueExpV4.MiniSeriesDTO;
    }
}

namespace leagueExpV4 {
    /**
     * MiniSeriesDTO data object, automatically generated.
     */
    export interface MiniSeriesDTO {
        losses?: int | null;
        progress?: string | null;
        target?: int | null;
        wins?: int | null;
    }
}

namespace leagueV4 {
    /**
     * LeagueListDTO data object, automatically generated.
     */
    export interface LeagueListDTO {
        leagueId?: string | null;
        entries?: Array<leagueV4.LeagueItemDTO> | null;
        tier?: string | null;
        name?: string | null;
        queue?: string | null;
    }
}

namespace leagueV4 {
    /**
     * LeagueItemDTO data object, automatically generated.
     */
    export interface LeagueItemDTO {
        freshBlood?: boolean | null;
        /** Winning team on Summoners Rift. */
        wins?: int | null;
        summonerName?: string | null;
        miniSeries: leagueV4.MiniSeriesDTO;
        inactive?: boolean | null;
        veteran?: boolean | null;
        hotStreak?: boolean | null;
        rank?: string | null;
        leaguePoints?: int | null;
        /** Losing team on Summoners Rift. */
        losses?: int | null;
        /** Player's encrypted summonerId. */
        summonerId?: string | null;
    }
}

namespace leagueV4 {
    /**
     * MiniSeriesDTO data object, automatically generated.
     */
    export interface MiniSeriesDTO {
        losses?: int | null;
        progress?: string | null;
        target?: int | null;
        wins?: int | null;
    }
}

namespace leagueV4 {
    /**
     * LeagueEntryDTO data object, automatically generated.
     */
    export interface LeagueEntryDTO {
        leagueId?: string | null;
        /** Player's encrypted summonerId. */
        summonerId?: string | null;
        summonerName?: string | null;
        queueType?: string | null;
        tier?: string | null;
        rank?: string | null;
        leaguePoints?: int | null;
        /** Winning team on Summoners Rift. */
        wins?: int | null;
        /** Losing team on Summoners Rift. */
        losses?: int | null;
        hotStreak?: boolean | null;
        veteran?: boolean | null;
        freshBlood?: boolean | null;
        inactive?: boolean | null;
        miniSeries: leagueV4.MiniSeriesDTO;
    }
}

namespace lolStatusV3 {
    /**
     * ShardStatus data object, automatically generated.
     */
    export interface ShardStatus {
        locales?: Array<string> | null;
        hostname?: string | null;
        name?: string | null;
        services?: Array<lolStatusV3.Service> | null;
        slug?: string | null;
        region_tag?: string | null;
    }
}

namespace lolStatusV3 {
    /**
     * Service data object, automatically generated.
     */
    export interface Service {
        incidents?: Array<lolStatusV3.Incident> | null;
        name?: string | null;
        slug?: string | null;
        status?: string | null;
    }
}

namespace lolStatusV3 {
    /**
     * Incident data object, automatically generated.
     */
    export interface Incident {
        active?: boolean | null;
        created_at?: string | null;
        id?: long | null;
        updates?: Array<lolStatusV3.Message> | null;
    }
}

namespace lolStatusV3 {
    /**
     * Message data object, automatically generated.
     */
    export interface Message {
        severity?: string | null;
        updated_at?: string | null;
        author?: string | null;
        translations?: Array<lolStatusV3.Translation> | null;
        created_at?: string | null;
        id?: string | null;
        content?: string | null;
    }
}

namespace lolStatusV3 {
    /**
     * Translation data object, automatically generated.
     */
    export interface Translation {
        locale?: string | null;
        content?: string | null;
        heading?: string | null;
    }
}

namespace lorRankedV1 {
    /**
     * LeaderboardDto data object, automatically generated.
     */
    export interface LeaderboardDto {
        /** A list of players in Master tier. */
        players?: Array<lorRankedV1.PlayerDto> | null;
    }
}

namespace lorRankedV1 {
    /**
     * PlayerDto data object, automatically generated.
     */
    export interface PlayerDto {
        name?: string | null;
        rank?: int | null;
    }
}

namespace matchV4 {
    /**
     * MatchDto data object, automatically generated.
     */
    export interface MatchDto {
        gameId?: long | null;
        /** Participant identity information. */
        participantIdentities?: Array<matchV4.ParticipantIdentityDto> | null;
        /** Please refer to the Game Constants documentation. */
        queueId?: int | null;
        /** Please refer to the Game Constants documentation. */
        gameType?: string | null;
        /** Match duration in seconds. */
        gameDuration?: long | null;
        /** Team information. */
        teams?: Array<matchV4.TeamStatsDto> | null;
        /** Platform where the match was played. */
        platformId?: string | null;
        /** Designates the timestamp when champion select ended and the loading screen appeared, NOT when the game timer was at 0:00. */
        gameCreation?: long | null;
        /** Please refer to the Game Constants documentation. */
        seasonId?: int | null;
        /** The major.minor version typically indicates the patch the match was played on. */
        gameVersion?: string | null;
        /** Please refer to the Game Constants documentation. */
        mapId?: int | null;
        /** Please refer to the Game Constants documentation. */
        gameMode?: string | null;
        /** Participant information. */
        participants?: Array<matchV4.ParticipantDto> | null;
    }
}

namespace matchV4 {
    /**
     * ParticipantIdentityDto data object, automatically generated.
     */
    export interface ParticipantIdentityDto {
        participantId?: int | null;
        /** Player information not included in the response for custom matches. Custom matches are considered private unless a tournament code was used to create the match. */
        player?: matchV4.PlayerDto | null;
    }
}

namespace matchV4 {
    /**
     * PlayerDto data object, automatically generated.
     */
    export interface PlayerDto {
        profileIcon?: int | null;
        /** Player's original accountId (Encrypted) */
        accountId?: string | null;
        matchHistoryUri?: string | null;
        /** Player's current accountId (Encrypted) */
        currentAccountId?: string | null;
        currentPlatformId?: string | null;
        summonerName?: string | null;
        /** Player's summonerId (Encrypted) */
        summonerId?: string | null;
        /** Original platformId. */
        platformId?: string | null;
    }
}

namespace matchV4 {
    /**
     * TeamStatsDto data object, automatically generated.
     */
    export interface TeamStatsDto {
        /** Number of towers the team destroyed. */
        towerKills?: int | null;
        /** Number of times the team killed Rift Herald. */
        riftHeraldKills?: int | null;
        /** Flag indicating whether or not the team scored the first blood. */
        firstBlood?: boolean | null;
        /** Number of inhibitors the team destroyed. */
        inhibitorKills?: int | null;
        /** If match queueId has a draft, contains banned champion data, otherwise empty. */
        bans?: Array<matchV4.TeamBansDto> | null;
        /** Flag indicating whether or not the team scored the first Baron kill. */
        firstBaron?: boolean | null;
        /** Flag indicating whether or not the team scored the first Dragon kill. */
        firstDragon?: boolean | null;
        /** For Dominion matches, specifies the points the team had at game end. */
        dominionVictoryScore?: int | null;
        /** Number of times the team killed Dragon. */
        dragonKills?: int | null;
        /** Number of times the team killed Baron. */
        baronKills?: int | null;
        /** Flag indicating whether or not the team destroyed the first inhibitor. */
        firstInhibitor?: boolean | null;
        /** Flag indicating whether or not the team destroyed the first tower. */
        firstTower?: boolean | null;
        /** Number of times the team killed Vilemaw. */
        vilemawKills?: int | null;
        /** Flag indicating whether or not the team scored the first Rift Herald kill. */
        firstRiftHerald?: boolean | null;
        /** 100 for blue side. 200 for red side. */
        teamId?: int | null;
        /** String indicating whether or not the team won. There are only two values visibile in public match history.
             (Legal values:  Fail,  Win) */
        win?: "Fail" | "Win" | null;
    }
}

namespace matchV4 {
    /**
     * TeamBansDto data object, automatically generated.
     */
    export interface TeamBansDto {
        /** Banned championId. */
        championId?: int | null;
        /** Turn during which the champion was banned. */
        pickTurn?: int | null;
    }
}

namespace matchV4 {
    /**
     * ParticipantDto data object, automatically generated.
     */
    export interface ParticipantDto {
        participantId?: int | null;
        championId?: int | null;
        /** List of legacy Rune information. Not included for matches played with Runes Reforged. */
        runes: Array<matchV4.RuneDto>;
        /** Participant statistics. */
        stats?: matchV4.ParticipantStatsDto | null;
        /** 100 for blue side. 200 for red side. */
        teamId?: int | null;
        /** Participant timeline data. */
        timeline?: matchV4.ParticipantTimelineDto | null;
        /** First Summoner Spell id. */
        spell1Id?: int | null;
        /** Second Summoner Spell id. */
        spell2Id?: int | null;
        /** Highest ranked tier achieved for the previous season in a specific subset of queueIds, if any, otherwise null. Used to display border in game loading screen. Please refer to the Ranked Info documentation.
             (Legal values:  CHALLENGER,  MASTER,  DIAMOND,  PLATINUM,  GOLD,  SILVER,  BRONZE,  UNRANKED) */
        highestAchievedSeasonTier: "CHALLENGER" | "MASTER" | "DIAMOND" | "PLATINUM" | "GOLD" | "SILVER" | "BRONZE" | "UNRANKED";
        /** List of legacy Mastery information. Not included for matches played with Runes Reforged. */
        masteries: Array<matchV4.MasteryDto>;
    }
}

namespace matchV4 {
    /**
     * RuneDto data object, automatically generated.
     */
    export interface RuneDto {
        runeId?: int | null;
        rank?: int | null;
    }
}

namespace matchV4 {
    /**
     * ParticipantStatsDto data object, automatically generated.
     */
    export interface ParticipantStatsDto {
        item0?: int | null;
        item2?: int | null;
        totalUnitsHealed?: int | null;
        item1?: int | null;
        largestMultiKill?: int | null;
        goldEarned?: int | null;
        firstInhibitorKill: boolean;
        physicalDamageTaken?: long | null;
        nodeNeutralizeAssist: int;
        totalPlayerScore: int;
        champLevel?: int | null;
        damageDealtToObjectives?: long | null;
        totalDamageTaken?: long | null;
        neutralMinionsKilled?: int | null;
        deaths?: int | null;
        tripleKills?: int | null;
        magicDamageDealtToChampions?: long | null;
        wardsKilled?: int | null;
        pentaKills?: int | null;
        damageSelfMitigated?: long | null;
        largestCriticalStrike?: int | null;
        nodeNeutralize: int;
        totalTimeCrowdControlDealt?: int | null;
        firstTowerKill: boolean;
        magicDamageDealt?: long | null;
        totalScoreRank: int;
        nodeCapture: int;
        wardsPlaced: int;
        totalDamageDealt?: long | null;
        timeCCingOthers?: long | null;
        magicalDamageTaken?: long | null;
        largestKillingSpree?: int | null;
        totalDamageDealtToChampions?: long | null;
        physicalDamageDealtToChampions?: long | null;
        neutralMinionsKilledTeamJungle?: int | null;
        totalMinionsKilled?: int | null;
        firstInhibitorAssist: boolean;
        visionWardsBoughtInGame?: int | null;
        objectivePlayerScore: int;
        kills?: int | null;
        firstTowerAssist: boolean;
        combatPlayerScore: int;
        inhibitorKills: int;
        turretKills: int;
        participantId?: int | null;
        trueDamageTaken?: long | null;
        firstBloodAssist: boolean;
        nodeCaptureAssist: int;
        assists?: int | null;
        teamObjective: int;
        altarsNeutralized: int;
        goldSpent?: int | null;
        damageDealtToTurrets?: long | null;
        altarsCaptured: int;
        win?: boolean | null;
        totalHeal?: long | null;
        unrealKills?: int | null;
        visionScore: long;
        physicalDamageDealt?: long | null;
        firstBloodKill: boolean;
        longestTimeSpentLiving?: int | null;
        killingSprees?: int | null;
        sightWardsBoughtInGame: int;
        trueDamageDealtToChampions?: long | null;
        neutralMinionsKilledEnemyJungle?: int | null;
        doubleKills?: int | null;
        trueDamageDealt?: long | null;
        quadraKills?: int | null;
        item4?: int | null;
        item3?: int | null;
        item6?: int | null;
        item5?: int | null;
        playerScore0: int;
        playerScore1: int;
        playerScore2: int;
        playerScore3: int;
        playerScore4: int;
        playerScore5: int;
        playerScore6: int;
        playerScore7: int;
        playerScore8: int;
        playerScore9: int;
        /** Primary path keystone rune. */
        perk0: int;
        /** Post game rune stats. */
        perk0Var1: int;
        /** Post game rune stats. */
        perk0Var2: int;
        /** Post game rune stats. */
        perk0Var3: int;
        /** Primary path rune. */
        perk1: int;
        /** Post game rune stats. */
        perk1Var1: int;
        /** Post game rune stats. */
        perk1Var2: int;
        /** Post game rune stats. */
        perk1Var3: int;
        /** Primary path rune. */
        perk2: int;
        /** Post game rune stats. */
        perk2Var1: int;
        /** Post game rune stats. */
        perk2Var2: int;
        /** Post game rune stats. */
        perk2Var3: int;
        /** Primary path rune. */
        perk3: int;
        /** Post game rune stats. */
        perk3Var1: int;
        /** Post game rune stats. */
        perk3Var2: int;
        /** Post game rune stats. */
        perk3Var3: int;
        /** Secondary path rune. */
        perk4: int;
        /** Post game rune stats. */
        perk4Var1: int;
        /** Post game rune stats. */
        perk4Var2: int;
        /** Post game rune stats. */
        perk4Var3: int;
        /** Secondary path rune. */
        perk5: int;
        /** Post game rune stats. */
        perk5Var1: int;
        /** Post game rune stats. */
        perk5Var2: int;
        /** Post game rune stats. */
        perk5Var3: int;
        /** Primary rune path */
        perkPrimaryStyle: int;
        /** Secondary rune path */
        perkSubStyle: int;
    }
}

namespace matchV4 {
    /**
     * ParticipantTimelineDto data object, automatically generated.
     */
    export interface ParticipantTimelineDto {
        participantId: int;
        /** Creep score difference versus the calculated lane opponent(s) for a specified period. */
        csDiffPerMinDeltas: { [key: string]: double };
        /** Damage taken for a specified period. */
        damageTakenPerMinDeltas: { [key: string]: double };
        /** Participant's calculated role.
             (Legal values:  DUO,  NONE,  SOLO,  DUO_CARRY,  DUO_SUPPORT) */
        role: "DUO" | "NONE" | "SOLO" | "DUO_CARRY" | "DUO_SUPPORT";
        /** Damage taken difference versus the calculated lane opponent(s) for a specified period. */
        damageTakenDiffPerMinDeltas: { [key: string]: double };
        /** Experience change for a specified period. */
        xpPerMinDeltas: { [key: string]: double };
        /** Experience difference versus the calculated lane opponent(s) for a specified period. */
        xpDiffPerMinDeltas: { [key: string]: double };
        /** Participant's calculated lane. MID and BOT are legacy values.
             (Legal values:  MID,  MIDDLE,  TOP,  JUNGLE,  BOT,  BOTTOM) */
        lane: "MID" | "MIDDLE" | "TOP" | "JUNGLE" | "BOT" | "BOTTOM";
        /** Creeps for a specified period. */
        creepsPerMinDeltas: { [key: string]: double };
        /** Gold for a specified period. */
        goldPerMinDeltas: { [key: string]: double };
    }
}

namespace matchV4 {
    /**
     * MasteryDto data object, automatically generated.
     */
    export interface MasteryDto {
        rank?: int | null;
        masteryId?: int | null;
    }
}

namespace matchV4 {
    /**
     * MatchlistDto data object, automatically generated.
     */
    export interface MatchlistDto {
        startIndex?: int | null;
        totalGames?: int | null;
        endIndex?: int | null;
        matches?: Array<matchV4.MatchReferenceDto> | null;
    }
}

namespace matchV4 {
    /**
     * MatchReferenceDto data object, automatically generated.
     */
    export interface MatchReferenceDto {
        gameId?: long | null;
        role?: string | null;
        season?: int | null;
        platformId?: string | null;
        champion?: int | null;
        queue?: int | null;
        lane?: string | null;
        timestamp?: long | null;
    }
}

namespace matchV4 {
    /**
     * MatchTimelineDto data object, automatically generated.
     */
    export interface MatchTimelineDto {
        frames?: Array<matchV4.MatchFrameDto> | null;
        frameInterval?: long | null;
    }
}

namespace matchV4 {
    /**
     * MatchFrameDto data object, automatically generated.
     */
    export interface MatchFrameDto {
        participantFrames?: { [key: string]: matchV4.MatchParticipantFrameDto } | null;
        events?: Array<matchV4.MatchEventDto> | null;
        timestamp?: long | null;
    }
}

namespace matchV4 {
    /**
     * MatchParticipantFrameDto data object, automatically generated.
     */
    export interface MatchParticipantFrameDto {
        participantId?: int | null;
        minionsKilled?: int | null;
        teamScore: int;
        dominionScore: int;
        totalGold?: int | null;
        level?: int | null;
        xp?: int | null;
        currentGold?: int | null;
        position: matchV4.MatchPositionDto;
        jungleMinionsKilled?: int | null;
    }
}

namespace matchV4 {
    /**
     * MatchPositionDto data object, automatically generated.
     */
    export interface MatchPositionDto {
        x?: int | null;
        y?: int | null;
    }
}

namespace matchV4 {
    /**
     * MatchEventDto data object, automatically generated.
     */
    export interface MatchEventDto {
        laneType: string;
        skillSlot: int;
        ascendedType: string;
        creatorId: int;
        afterId: int;
        eventType: string;
        /** (Legal values:  CHAMPION_KILL,  WARD_PLACED,  WARD_KILL,  BUILDING_KILL,  ELITE_MONSTER_KILL,  ITEM_PURCHASED,  ITEM_SOLD,  ITEM_DESTROYED,  ITEM_UNDO,  SKILL_LEVEL_UP,  ASCENDED_EVENT,  CAPTURE_POINT,  PORO_KING_SUMMON) */
        type?: "CHAMPION_KILL" | "WARD_PLACED" | "WARD_KILL" | "BUILDING_KILL" | "ELITE_MONSTER_KILL" | "ITEM_PURCHASED" | "ITEM_SOLD" | "ITEM_DESTROYED" | "ITEM_UNDO" | "SKILL_LEVEL_UP" | "ASCENDED_EVENT" | "CAPTURE_POINT" | "PORO_KING_SUMMON" | null;
        levelUpType: string;
        wardType: string;
        participantId: int;
        towerType: string;
        itemId: int;
        beforeId: int;
        pointCaptured: string;
        monsterType: string;
        monsterSubType: string;
        teamId: int;
        position: matchV4.MatchPositionDto;
        killerId: int;
        timestamp?: long | null;
        assistingParticipantIds: Array<int>;
        buildingType: string;
        victimId: int;
    }
}

namespace spectatorV4 {
    /**
     * CurrentGameInfo data object, automatically generated.
     */
    export interface CurrentGameInfo {
        /** The ID of the game */
        gameId?: long | null;
        /** The game type */
        gameType?: string | null;
        /** The game start time represented in epoch milliseconds */
        gameStartTime?: long | null;
        /** The ID of the map */
        mapId?: long | null;
        /** The amount of time in seconds that has passed since the game started */
        gameLength?: long | null;
        /** The ID of the platform on which the game is being played */
        platformId?: string | null;
        /** The game mode */
        gameMode?: string | null;
        /** Banned champion information */
        bannedChampions?: Array<spectatorV4.BannedChampion> | null;
        /** The queue type (queue types are documented on the Game Constants page) */
        gameQueueConfigId: long;
        /** The observer information */
        observers?: spectatorV4.Observer | null;
        /** The participant information */
        participants?: Array<spectatorV4.CurrentGameParticipant> | null;
    }
}

namespace spectatorV4 {
    /**
     * BannedChampion data object, automatically generated.
     */
    export interface BannedChampion {
        /** The turn during which the champion was banned */
        pickTurn?: int | null;
        /** The ID of the banned champion */
        championId?: long | null;
        /** The ID of the team that banned the champion */
        teamId?: long | null;
    }
}

namespace spectatorV4 {
    /**
     * Observer data object, automatically generated.
     */
    export interface Observer {
        /** Key used to decrypt the spectator grid game data for playback */
        encryptionKey?: string | null;
    }
}

namespace spectatorV4 {
    /**
     * CurrentGameParticipant data object, automatically generated.
     */
    export interface CurrentGameParticipant {
        /** The ID of the champion played by this participant */
        championId?: long | null;
        /** Perks/Runes Reforged Information */
        perks?: spectatorV4.Perks | null;
        /** The ID of the profile icon used by this participant */
        profileIconId?: long | null;
        /** Flag indicating whether or not this participant is a bot */
        bot?: boolean | null;
        /** The team ID of this participant, indicating the participant's team */
        teamId?: long | null;
        /** The summoner name of this participant */
        summonerName?: string | null;
        /** The encrypted summoner ID of this participant */
        summonerId?: string | null;
        /** The ID of the first summoner spell used by this participant */
        spell1Id?: long | null;
        /** The ID of the second summoner spell used by this participant */
        spell2Id?: long | null;
        /** List of Game Customizations */
        gameCustomizationObjects?: Array<spectatorV4.GameCustomizationObject> | null;
    }
}

namespace spectatorV4 {
    /**
     * Perks data object, automatically generated.
     */
    export interface Perks {
        /** IDs of the perks/runes assigned. */
        perkIds?: Array<long> | null;
        /** Primary runes path */
        perkStyle?: long | null;
        /** Secondary runes path */
        perkSubStyle?: long | null;
    }
}

namespace spectatorV4 {
    /**
     * GameCustomizationObject data object, automatically generated.
     */
    export interface GameCustomizationObject {
        /** Category identifier for Game Customization */
        category?: string | null;
        /** Game Customization content */
        content?: string | null;
    }
}

namespace spectatorV4 {
    /**
     * FeaturedGames data object, automatically generated.
     */
    export interface FeaturedGames {
        /** The list of featured games */
        gameList?: Array<spectatorV4.FeaturedGameInfo> | null;
        /** The suggested interval to wait before requesting FeaturedGames again */
        clientRefreshInterval?: long | null;
    }
}

namespace spectatorV4 {
    /**
     * FeaturedGameInfo data object, automatically generated.
     */
    export interface FeaturedGameInfo {
        /** The game mode
             (Legal values:  CLASSIC,  ODIN,  ARAM,  TUTORIAL,  ONEFORALL,  ASCENSION,  FIRSTBLOOD,  KINGPORO) */
        gameMode?: "CLASSIC" | "ODIN" | "ARAM" | "TUTORIAL" | "ONEFORALL" | "ASCENSION" | "FIRSTBLOOD" | "KINGPORO" | null;
        /** The amount of time in seconds that has passed since the game started */
        gameLength?: long | null;
        /** The ID of the map */
        mapId?: long | null;
        /** The game type
             (Legal values:  CUSTOM_GAME,  MATCHED_GAME,  TUTORIAL_GAME) */
        gameType?: "CUSTOM_GAME" | "MATCHED_GAME" | "TUTORIAL_GAME" | null;
        /** Banned champion information */
        bannedChampions?: Array<spectatorV4.BannedChampion> | null;
        /** The ID of the game */
        gameId?: long | null;
        /** The observer information */
        observers?: spectatorV4.Observer | null;
        /** The queue type (queue types are documented on the Game Constants page) */
        gameQueueConfigId?: long | null;
        /** The game start time represented in epoch milliseconds */
        gameStartTime?: long | null;
        /** The participant information */
        participants?: Array<spectatorV4.Participant> | null;
        /** The ID of the platform on which the game is being played */
        platformId?: string | null;
    }
}

namespace spectatorV4 {
    /**
     * Participant data object, automatically generated.
     */
    export interface Participant {
        /** Flag indicating whether or not this participant is a bot */
        bot?: boolean | null;
        /** The ID of the second summoner spell used by this participant */
        spell2Id?: long | null;
        /** The ID of the profile icon used by this participant */
        profileIconId?: long | null;
        /** The summoner name of this participant */
        summonerName?: string | null;
        /** The ID of the champion played by this participant */
        championId?: long | null;
        /** The team ID of this participant, indicating the participant's team */
        teamId?: long | null;
        /** The ID of the first summoner spell used by this participant */
        spell1Id?: long | null;
    }
}

namespace summonerV4 {
    /**
     * SummonerDTO data object, automatically generated.
     * # Description
     * represents a summoner
     */
    export interface SummonerDTO {
        /** Encrypted account ID. Max length 56 characters. */
        accountId?: string | null;
        /** ID of the summoner icon associated with the summoner. */
        profileIconId?: int | null;
        /** Date summoner was last modified specified as epoch milliseconds. The following events will update this timestamp: profile icon change, playing the tutorial or advanced tutorial, finishing a game, summoner name change */
        revisionDate?: long | null;
        /** Summoner name. */
        name?: string | null;
        /** Encrypted summoner ID. Max length 63 characters. */
        id?: string | null;
        /** Encrypted PUUID. Exact length of 78 characters. */
        puuid?: string | null;
        /** Summoner level associated with the summoner. */
        summonerLevel?: long | null;
    }
}

namespace tftLeagueV1 {
    /**
     * LeagueListDTO data object, automatically generated.
     */
    export interface LeagueListDTO {
        leagueId?: string | null;
        entries?: Array<tftLeagueV1.LeagueItemDTO> | null;
        tier?: string | null;
        name?: string | null;
        queue?: string | null;
    }
}

namespace tftLeagueV1 {
    /**
     * LeagueItemDTO data object, automatically generated.
     */
    export interface LeagueItemDTO {
        freshBlood?: boolean | null;
        /** First placement. */
        wins?: int | null;
        summonerName?: string | null;
        miniSeries: tftLeagueV1.MiniSeriesDTO;
        inactive?: boolean | null;
        veteran?: boolean | null;
        hotStreak?: boolean | null;
        rank?: string | null;
        leaguePoints?: int | null;
        /** Second through eighth placement. */
        losses?: int | null;
        /** Player's encrypted summonerId. */
        summonerId?: string | null;
    }
}

namespace tftLeagueV1 {
    /**
     * MiniSeriesDTO data object, automatically generated.
     */
    export interface MiniSeriesDTO {
        losses?: int | null;
        progress?: string | null;
        target?: int | null;
        wins?: int | null;
    }
}

namespace tftLeagueV1 {
    /**
     * LeagueEntryDTO data object, automatically generated.
     */
    export interface LeagueEntryDTO {
        leagueId?: string | null;
        /** Player's encrypted summonerId. */
        summonerId?: string | null;
        summonerName?: string | null;
        queueType?: string | null;
        tier?: string | null;
        rank?: string | null;
        leaguePoints?: int | null;
        /** First placement. */
        wins?: int | null;
        /** Second through eighth placement. */
        losses?: int | null;
        hotStreak?: boolean | null;
        veteran?: boolean | null;
        freshBlood?: boolean | null;
        inactive?: boolean | null;
        miniSeries: tftLeagueV1.MiniSeriesDTO;
    }
}

namespace tftMatchV1 {
    /**
     * MatchDto data object, automatically generated.
     */
    export interface MatchDto {
        /** Match metadata. */
        metadata?: tftMatchV1.MetadataDto | null;
        /** Match info. */
        info?: tftMatchV1.InfoDto | null;
    }
}

namespace tftMatchV1 {
    /**
     * MetadataDto data object, automatically generated.
     */
    export interface MetadataDto {
        /** Match data version. */
        data_version?: string | null;
        /** Match id. */
        match_id?: string | null;
        /** A list of encrypted participant PUUIDs. */
        participants?: Array<string> | null;
    }
}

namespace tftMatchV1 {
    /**
     * InfoDto data object, automatically generated.
     */
    export interface InfoDto {
        /** Unix timestamp. */
        game_datetime?: long | null;
        /** Game length in seconds. */
        game_length?: float | null;
        /** Game variation enum, i.e. "TFT3_GameVariation_BigLittleLegends", missing from official Riot API docs. */
        game_variation: string;
        /** Game client version. */
        game_version?: string | null;
        /** Participants. */
        participants?: Array<tftMatchV1.ParticipantDto> | null;
        /** Please refer to the League of Legends documentation. */
        queue_id?: int | null;
        /** Teamfight Tactics set number. */
        tft_set_number?: int | null;
    }
}

namespace tftMatchV1 {
    /**
     * ParticipantDto data object, automatically generated.
     */
    export interface ParticipantDto {
        /** Participant's companion. */
        companion?: tftMatchV1.CompanionDto | null;
        /** Gold left after participant was eliminated. */
        gold_left?: int | null;
        /** The round the participant was eliminated in. Note: If the player was eliminated in stage 2-1 their last_round would be 5. */
        last_round?: int | null;
        /** Participant Little Legend level. Note: This is not the number of active units. */
        level?: int | null;
        /** Participant placement upon elimination. */
        placement?: int | null;
        /** Number of players the participant eliminated. */
        players_eliminated?: int | null;
        /** Encrypted PUUID. */
        puuid?: string | null;
        /** The number of seconds before the participant was eliminated. */
        time_eliminated?: float | null;
        /** Damage the participant dealt to other players. */
        total_damage_to_players?: int | null;
        /** A complete list of traits for the participant's active units. */
        traits?: Array<tftMatchV1.TraitDto> | null;
        /** A list of active units for the participant. */
        units?: Array<tftMatchV1.UnitDto> | null;
    }
}

namespace tftMatchV1 {
    /**
     * TraitDto data object, automatically generated.
     */
    export interface TraitDto {
        /** Trait name. */
        name?: string | null;
        /** Number of units with this trait. */
        num_units?: int | null;
        /** Current active tier for the trait. */
        tier_current?: int | null;
        /** Total tiers for the trait. */
        tier_total: int;
    }
}

namespace tftMatchV1 {
    /**
     * UnitDto data object, automatically generated.
     */
    export interface UnitDto {
        /** A list of the unit's items. Please refer to the Teamfight Tactics documentation for item ids. */
        items?: Array<int> | null;
        /** This field was introduced in patch 9.22 with data_version 2. */
        character_id?: string | null;
        /** Unit name. */
        name?: string | null;
        /** Unit rarity. This doesn't equate to the unit cost. */
        rarity?: int | null;
        /** Unit tier. */
        tier?: int | null;
    }
}

namespace tftMatchV1 {
    /**
     * CompanionDto data object, automatically generated.
     */
    export interface CompanionDto {
        skin_ID?: int | null;
        content_ID?: string | null;
        species?: string | null;
    }
}

namespace tftSummonerV1 {
    /**
     * SummonerDTO data object, automatically generated.
     * # Description
     * represents a summoner
     */
    export interface SummonerDTO {
        /** ID of the summoner icon associated with the summoner. */
        profileIconId?: int | null;
        /** Summoner name. */
        name?: string | null;
        /** Encrypted PUUID. Exact length of 78 characters. */
        puuid?: string | null;
        /** Summoner level associated with the summoner. */
        summonerLevel?: long | null;
        /** Date summoner was last modified specified as epoch milliseconds. The following events will update this timestamp: profile icon change, playing the tutorial or advanced tutorial, finishing a game, summoner name change */
        revisionDate?: long | null;
        /** Encrypted summoner ID. Max length 63 characters. */
        id?: string | null;
        /** Encrypted account ID. Max length 56 characters. */
        accountId?: string | null;
    }
}

namespace tournamentStubV4 {
    /**
     * TournamentCodeParameters data object, automatically generated.
     */
    export interface TournamentCodeParameters {
        /** Optional list of encrypted summonerIds in order to validate the players eligible to join the lobby. NOTE: We currently do not enforce participants at the team level, but rather the aggregate of teamOne and teamTwo. We may add the ability to enforce at the team level in the future. */
        allowedSummonerIds: Array<string>;
        /** Optional string that may contain any data in any format, if specified at all. Used to denote any custom information about the game. */
        metadata: string;
        /** The team size of the game. Valid values are 1-5. */
        teamSize?: int | null;
        /** The pick type of the game.
             (Legal values:  BLIND_PICK,  DRAFT_MODE,  ALL_RANDOM,  TOURNAMENT_DRAFT) */
        pickType?: "BLIND_PICK" | "DRAFT_MODE" | "ALL_RANDOM" | "TOURNAMENT_DRAFT" | null;
        /** The map type of the game.
             (Legal values:  SUMMONERS_RIFT,  TWISTED_TREELINE,  HOWLING_ABYSS) */
        mapType?: "SUMMONERS_RIFT" | "TWISTED_TREELINE" | "HOWLING_ABYSS" | null;
        /** The spectator type of the game.
             (Legal values:  NONE,  LOBBYONLY,  ALL) */
        spectatorType?: "NONE" | "LOBBYONLY" | "ALL" | null;
    }
}

namespace tournamentStubV4 {
    /**
     * LobbyEventDTOWrapper data object, automatically generated.
     */
    export interface LobbyEventDTOWrapper {
        eventList?: Array<tournamentStubV4.LobbyEventDTO> | null;
    }
}

namespace tournamentStubV4 {
    /**
     * LobbyEventDTO data object, automatically generated.
     */
    export interface LobbyEventDTO {
        /** The summonerId that triggered the event (Encrypted) */
        summonerId?: string | null;
        /** The type of event that was triggered */
        eventType?: string | null;
        /** Timestamp from the event */
        timestamp?: string | null;
    }
}

namespace tournamentStubV4 {
    /**
     * ProviderRegistrationParameters data object, automatically generated.
     */
    export interface ProviderRegistrationParameters {
        /** The region in which the provider will be running tournaments.
             (Legal values:  BR,  EUNE,  EUW,  JP,  LAN,  LAS,  NA,  OCE,  PBE,  RU,  TR) */
        region?: "BR" | "EUNE" | "EUW" | "JP" | "LAN" | "LAS" | "NA" | "OCE" | "PBE" | "RU" | "TR" | null;
        /** The provider's callback URL to which tournament game results in this region should be posted. The URL must be well-formed, use the http or https protocol, and use the default port for the protocol (http URLs must use port 80, https URLs must use port 443). */
        url?: string | null;
    }
}

namespace tournamentStubV4 {
    /**
     * TournamentRegistrationParameters data object, automatically generated.
     */
    export interface TournamentRegistrationParameters {
        /** The provider ID to specify the regional registered provider data to associate this tournament. */
        providerId?: int | null;
        /** The optional name of the tournament. */
        name: string;
    }
}

namespace tournamentV4 {
    /**
     * TournamentCodeParameters data object, automatically generated.
     */
    export interface TournamentCodeParameters {
        /** Optional list of encrypted summonerIds in order to validate the players eligible to join the lobby. NOTE: We currently do not enforce participants at the team level, but rather the aggregate of teamOne and teamTwo. We may add the ability to enforce at the team level in the future. */
        allowedSummonerIds: Array<string>;
        /** Optional string that may contain any data in any format, if specified at all. Used to denote any custom information about the game. */
        metadata: string;
        /** The team size of the game. Valid values are 1-5. */
        teamSize?: int | null;
        /** The pick type of the game.
             (Legal values:  BLIND_PICK,  DRAFT_MODE,  ALL_RANDOM,  TOURNAMENT_DRAFT) */
        pickType?: "BLIND_PICK" | "DRAFT_MODE" | "ALL_RANDOM" | "TOURNAMENT_DRAFT" | null;
        /** The map type of the game.
             (Legal values:  SUMMONERS_RIFT,  TWISTED_TREELINE,  HOWLING_ABYSS) */
        mapType?: "SUMMONERS_RIFT" | "TWISTED_TREELINE" | "HOWLING_ABYSS" | null;
        /** The spectator type of the game.
             (Legal values:  NONE,  LOBBYONLY,  ALL) */
        spectatorType?: "NONE" | "LOBBYONLY" | "ALL" | null;
    }
}

namespace tournamentV4 {
    /**
     * TournamentCodeDTO data object, automatically generated.
     */
    export interface TournamentCodeDTO {
        /** The tournament code. */
        code?: string | null;
        /** The spectator mode for the tournament code game. */
        spectators?: string | null;
        /** The lobby name for the tournament code game. */
        lobbyName?: string | null;
        /** The metadata for tournament code. */
        metaData?: string | null;
        /** The password for the tournament code game. */
        password?: string | null;
        /** The team size for the tournament code game. */
        teamSize?: int | null;
        /** The provider's ID. */
        providerId?: int | null;
        /** The pick mode for tournament code game. */
        pickType?: string | null;
        /** The tournament's ID. */
        tournamentId?: int | null;
        /** The tournament code's ID. */
        id?: int | null;
        /** The tournament code's region.
             (Legal values:  BR,  EUNE,  EUW,  JP,  LAN,  LAS,  NA,  OCE,  PBE,  RU,  TR) */
        region?: "BR" | "EUNE" | "EUW" | "JP" | "LAN" | "LAS" | "NA" | "OCE" | "PBE" | "RU" | "TR" | null;
        /** The game map for the tournament code game */
        map?: string | null;
        /** The summonerIds of the participants (Encrypted) */
        participants?: Array<string> | null;
    }
}

namespace tournamentV4 {
    /**
     * TournamentCodeUpdateParameters data object, automatically generated.
     */
    export interface TournamentCodeUpdateParameters {
        /** Optional list of encrypted summonerIds in order to validate the players eligible to join the lobby. NOTE: We currently do not enforce participants at the team level, but rather the aggregate of teamOne and teamTwo. We may add the ability to enforce at the team level in the future. */
        allowedSummonerIds: Array<string>;
        /** The pick type
             (Legal values:  BLIND_PICK,  DRAFT_MODE,  ALL_RANDOM,  TOURNAMENT_DRAFT) */
        pickType?: "BLIND_PICK" | "DRAFT_MODE" | "ALL_RANDOM" | "TOURNAMENT_DRAFT" | null;
        /** The map type
             (Legal values:  SUMMONERS_RIFT,  TWISTED_TREELINE,  HOWLING_ABYSS) */
        mapType?: "SUMMONERS_RIFT" | "TWISTED_TREELINE" | "HOWLING_ABYSS" | null;
        /** The spectator type
             (Legal values:  NONE,  LOBBYONLY,  ALL) */
        spectatorType?: "NONE" | "LOBBYONLY" | "ALL" | null;
    }
}

namespace tournamentV4 {
    /**
     * LobbyEventDTOWrapper data object, automatically generated.
     */
    export interface LobbyEventDTOWrapper {
        eventList?: Array<tournamentV4.LobbyEventDTO> | null;
    }
}

namespace tournamentV4 {
    /**
     * LobbyEventDTO data object, automatically generated.
     */
    export interface LobbyEventDTO {
        /** Timestamp from the event */
        timestamp?: string | null;
        /** The type of event that was triggered */
        eventType?: string | null;
        /** The summonerId that triggered the event (Encrypted) */
        summonerId?: string | null;
    }
}

namespace tournamentV4 {
    /**
     * ProviderRegistrationParameters data object, automatically generated.
     */
    export interface ProviderRegistrationParameters {
        /** The region in which the provider will be running tournaments.
             (Legal values:  BR,  EUNE,  EUW,  JP,  LAN,  LAS,  NA,  OCE,  PBE,  RU,  TR) */
        region?: "BR" | "EUNE" | "EUW" | "JP" | "LAN" | "LAS" | "NA" | "OCE" | "PBE" | "RU" | "TR" | null;
        /** The provider's callback URL to which tournament game results in this region should be posted. The URL must be well-formed, use the http or https protocol, and use the default port for the protocol (http URLs must use port 80, https URLs must use port 443). */
        url?: string | null;
    }
}

namespace tournamentV4 {
    /**
     * TournamentRegistrationParameters data object, automatically generated.
     */
    export interface TournamentRegistrationParameters {
        /** The provider ID to specify the regional registered provider data to associate this tournament. */
        providerId?: int | null;
        /** The optional name of the tournament. */
        name: string;
    }
}
