///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// http://www.mingweisamuel.com/riotapi-schema/tool/
// Version 909460d67267a0122544094d93120b50f8d0f5de


interface RiotApi {
    /** Handle for accessing ChampionMasteryV4 methods. */
    readonly championMasteryV4: ChampionMasteryV4;
    /** Handle for accessing ChampionV3 methods. */
    readonly championV3: ChampionV3;
    /** Handle for accessing ClashV1 methods. */
    readonly clashV1: ClashV1;
    /** Handle for accessing LeagueExpV4 methods. */
    readonly leagueExpV4: LeagueExpV4;
    /** Handle for accessing LeagueV4 methods. */
    readonly leagueV4: LeagueV4;
    /** Handle for accessing LolStatusV3 methods. */
    readonly lolStatusV3: LolStatusV3;
    /** Handle for accessing LorRankedV1 methods. */
    readonly lorRankedV1: LorRankedV1;
    /** Handle for accessing MatchV4 methods. */
    readonly matchV4: MatchV4;
    /** Handle for accessing SpectatorV4 methods. */
    readonly spectatorV4: SpectatorV4;
    /** Handle for accessing SummonerV4 methods. */
    readonly summonerV4: SummonerV4;
    /** Handle for accessing TftLeagueV1 methods. */
    readonly tftLeagueV1: TftLeagueV1;
    /** Handle for accessing TftMatchV1 methods. */
    readonly tftMatchV1: TftMatchV1;
    /** Handle for accessing TftSummonerV1 methods. */
    readonly tftSummonerV1: TftSummonerV1;
    /** Handle for accessing ThirdPartyCodeV4 methods. */
    readonly thirdPartyCodeV4: ThirdPartyCodeV4;
    /** Handle for accessing TournamentStubV4 methods. */
    readonly tournamentStubV4: TournamentStubV4;
    /** Handle for accessing TournamentV4 methods. */
    readonly tournamentV4: TournamentV4;
}


/**
 * ChampionMasteryV4 endpoints handle, accessed via `RiotApi.championMasteryV4`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#champion-mastery-v4" target="_blank">`champion-mastery-v4`</a>
 * 
 * Note: this is automatically generated.
 */
interface ChampionMasteryV4 {
    /**
     * Get all champion mastery entries sorted by number of champion points descending,
     */
    getAllChampionMasteries(region: Region, args?: object | Array<any>): Array<championMasteryV4.ChampionMasteryDTO>;
    /**
     * Get a champion mastery by player ID and champion ID.
     */
    getChampionMastery(region: Region, args?: object | Array<any>): championMasteryV4.ChampionMasteryDTO | null;
    /**
     * Get a player's total champion mastery score, which is the sum of individual champion mastery levels.
     */
    getChampionMasteryScore(region: Region, args?: object | Array<any>): int;
}

/**
 * ChampionV3 endpoints handle, accessed via `RiotApi.championV3`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#champion-v3" target="_blank">`champion-v3`</a>
 * 
 * Note: this is automatically generated.
 */
interface ChampionV3 {
    /**
     * Returns champion rotations, including free-to-play and low-level free-to-play rotations (REST)
     */
    getChampionInfo(region: Region, args?: object | Array<any>): championV3.ChampionInfo;
}

/**
 * ClashV1 endpoints handle, accessed via `RiotApi.clashV1`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#clash-v1" target="_blank">`clash-v1`</a>
 * 
 * Note: this is automatically generated.
 */
interface ClashV1 {
    /**
     * Get players by summoner ID.
     * ## Implementation Notes
     * This endpoint returns a list of active Clash players for a given summoner ID. If a summoner registers for multiple tournaments at the same time (e.g., Saturday and Sunday) then both registrations would appear in this list.
     */
    getPlayersBySummoner(region: Region, args?: object | Array<any>): Array<clashV1.PlayerDto>;
    /**
     * Get team by ID.
     */
    getTeamById(region: Region, args?: object | Array<any>): clashV1.TeamDto | null;
    /**
     * Get all active or upcoming tournaments.
     */
    getTournaments(region: Region, args?: object | Array<any>): Array<clashV1.TournamentDto>;
    /**
     * Get tournament by team ID.
     */
    getTournamentByTeam(region: Region, args?: object | Array<any>): clashV1.TournamentDto | null;
    /**
     * Get tournament by ID.
     */
    getTournamentById(region: Region, args?: object | Array<any>): clashV1.TournamentDto | null;
}

/**
 * LeagueExpV4 endpoints handle, accessed via `RiotApi.leagueExpV4`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#league-exp-v4" target="_blank">`league-exp-v4`</a>
 * 
 * Note: this is automatically generated.
 */
interface LeagueExpV4 {
    /**
     * Get all the league entries.
     */
    getLeagueEntries(region: Region, args?: object | Array<any>): Array<leagueExpV4.LeagueEntryDTO>;
}

/**
 * LeagueV4 endpoints handle, accessed via `RiotApi.leagueV4`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#league-v4" target="_blank">`league-v4`</a>
 * 
 * Note: this is automatically generated.
 */
interface LeagueV4 {
    /**
     * Get the challenger league for given queue.
     */
    getChallengerLeague(region: Region, args?: object | Array<any>): leagueV4.LeagueListDTO;
    /**
     * Get league entries in all queues for a given summoner ID.
     */
    getLeagueEntriesForSummoner(region: Region, args?: object | Array<any>): Array<leagueV4.LeagueEntryDTO>;
    /**
     * Get all the league entries.
     */
    getLeagueEntries(region: Region, args?: object | Array<any>): Array<leagueV4.LeagueEntryDTO>;
    /**
     * Get the grandmaster league of a specific queue.
     */
    getGrandmasterLeague(region: Region, args?: object | Array<any>): leagueV4.LeagueListDTO;
    /**
     * Get league with given ID, including inactive entries.
     */
    getLeagueById(region: Region, args?: object | Array<any>): leagueV4.LeagueListDTO | null;
    /**
     * Get the master league for given queue.
     */
    getMasterLeague(region: Region, args?: object | Array<any>): leagueV4.LeagueListDTO;
}

/**
 * LolStatusV3 endpoints handle, accessed via `RiotApi.lolStatusV3`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#lol-status-v3" target="_blank">`lol-status-v3`</a>
 * 
 * Note: this is automatically generated.
 */
interface LolStatusV3 {
    /**
     * Get League of Legends status for the given shard.
     * ## Rate Limit Notes
     * Requests to this API are not counted against the application Rate Limits.
     */
    getShardData(region: Region, args?: object | Array<any>): lolStatusV3.ShardStatus;
}

/**
 * LorRankedV1 endpoints handle, accessed via `RiotApi.lorRankedV1`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#lor-ranked-v1" target="_blank">`lor-ranked-v1`</a>
 * 
 * Note: this is automatically generated.
 */
interface LorRankedV1 {
    /**
     * Get the players in Master tier.
     */
    getLeaderboards(region: Region, args?: object | Array<any>): lorRankedV1.LeaderboardDto;
}

/**
 * MatchV4 endpoints handle, accessed via `RiotApi.matchV4`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#match-v4" target="_blank">`match-v4`</a>
 * 
 * Note: this is automatically generated.
 */
interface MatchV4 {
    /**
     * Get match IDs by tournament code.
     */
    getMatchIdsByTournamentCode(region: Region, args?: object | Array<any>): Array<long>;
    /**
     * Get match by match ID.
     */
    getMatch(region: Region, args?: object | Array<any>): matchV4.MatchDto | null;
    /**
     * Get match by match ID and tournament code.
     */
    getMatchByTournamentCode(region: Region, args?: object | Array<any>): matchV4.MatchDto;
    /**
     * Get matchlist for games played on given account ID and platform ID and filtered using given filter parameters, if any.
     * ## Implementation Notes
     * A number of optional parameters are provided for filtering. It is up to the caller to ensure that the combination of filter parameters provided is valid for the requested account, otherwise, no matches may be returned.
     * 
     * If beginIndex is specified, but not endIndex, then endIndex defaults to beginIndex+100. If endIndex is specified, but not beginIndex, then beginIndex defaults to 0. If both are specified, then endIndex must be greater than beginIndex. The maximum range allowed is 100, otherwise a 400 error code is returned.
     * 
     * If beginTime is specified, but not endTime, then endTime defaults to the the current unix timestamp in milliseconds (the maximum time range limitation is not observed in this specific case). If endTime is specified, but not beginTime, then beginTime defaults to the start of the account's match history returning a 400 due to the maximum time range limitation. If both are specified, then endTime should be greater than beginTime. The maximum time range allowed is one week, otherwise a 400 error code is returned.
     */
    getMatchlist(region: Region, args?: object | Array<any>): matchV4.MatchlistDto | null;
    /**
     * Get match timeline by match ID.
     * ## Implementation Notes
     * Not all matches have timeline data.
     */
    getMatchTimeline(region: Region, args?: object | Array<any>): matchV4.MatchTimelineDto | null;
}

/**
 * SpectatorV4 endpoints handle, accessed via `RiotApi.spectatorV4`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#spectator-v4" target="_blank">`spectator-v4`</a>
 * 
 * Note: this is automatically generated.
 */
interface SpectatorV4 {
    /**
     * Get current game information for the given summoner ID.
     */
    getCurrentGameInfoBySummoner(region: Region, args?: object | Array<any>): spectatorV4.CurrentGameInfo | null;
    /**
     * Get list of featured games.
     */
    getFeaturedGames(region: Region, args?: object | Array<any>): spectatorV4.FeaturedGames;
}

/**
 * SummonerV4 endpoints handle, accessed via `RiotApi.summonerV4`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#summoner-v4" target="_blank">`summoner-v4`</a>
 * 
 * Note: this is automatically generated.
 */
interface SummonerV4 {
    /**
     * Get a summoner by account ID.
     */
    getByAccountId(region: Region, args?: object | Array<any>): summonerV4.SummonerDTO;
    /**
     * Get a summoner by summoner name.
     */
    getBySummonerName(region: Region, args?: object | Array<any>): summonerV4.SummonerDTO | null;
    /**
     * Get a summoner by PUUID.
     */
    getByPUUID(region: Region, args?: object | Array<any>): summonerV4.SummonerDTO;
    /**
     * Get a summoner by summoner ID.
     */
    getBySummonerId(region: Region, args?: object | Array<any>): summonerV4.SummonerDTO;
}

/**
 * TftLeagueV1 endpoints handle, accessed via `RiotApi.tftLeagueV1`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#tft-league-v1" target="_blank">`tft-league-v1`</a>
 * 
 * Note: this is automatically generated.
 */
interface TftLeagueV1 {
    /**
     * Get the challenger league.
     */
    getChallengerLeague(region: Region, args?: object | Array<any>): tftLeagueV1.LeagueListDTO;
    /**
     * Get league entries for a given summoner ID.
     */
    getLeagueEntriesForSummoner(region: Region, args?: object | Array<any>): Array<tftLeagueV1.LeagueEntryDTO>;
    /**
     * Get all the league entries.
     */
    getLeagueEntries(region: Region, args?: object | Array<any>): Array<tftLeagueV1.LeagueEntryDTO>;
    /**
     * Get the grandmaster league.
     */
    getGrandmasterLeague(region: Region, args?: object | Array<any>): tftLeagueV1.LeagueListDTO;
    /**
     * Get league with given ID, including inactive entries.
     */
    getLeagueById(region: Region, args?: object | Array<any>): tftLeagueV1.LeagueListDTO | null;
    /**
     * Get the master league.
     */
    getMasterLeague(region: Region, args?: object | Array<any>): tftLeagueV1.LeagueListDTO;
}

/**
 * TftMatchV1 endpoints handle, accessed via `RiotApi.tftMatchV1`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#tft-match-v1" target="_blank">`tft-match-v1`</a>
 * 
 * Note: this is automatically generated.
 */
interface TftMatchV1 {
    /**
     * Get a list of match ids by PUUID.
     */
    getMatchIdsByPUUID(region: Region, args?: object | Array<any>): Array<string>;
    /**
     * Get a match by match id.
     */
    getMatch(region: Region, args?: object | Array<any>): tftMatchV1.MatchDto | null;
}

/**
 * TftSummonerV1 endpoints handle, accessed via `RiotApi.tftSummonerV1`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#tft-summoner-v1" target="_blank">`tft-summoner-v1`</a>
 * 
 * Note: this is automatically generated.
 */
interface TftSummonerV1 {
    /**
     * Get a summoner by account ID.
     */
    getByAccountId(region: Region, args?: object | Array<any>): tftSummonerV1.SummonerDTO;
    /**
     * Get a summoner by summoner name.
     */
    getBySummonerName(region: Region, args?: object | Array<any>): tftSummonerV1.SummonerDTO | null;
    /**
     * Get a summoner by PUUID.
     */
    getByPUUID(region: Region, args?: object | Array<any>): tftSummonerV1.SummonerDTO;
    /**
     * Get a summoner by summoner ID.
     */
    getBySummonerId(region: Region, args?: object | Array<any>): tftSummonerV1.SummonerDTO;
}

/**
 * ThirdPartyCodeV4 endpoints handle, accessed via `RiotApi.thirdPartyCodeV4`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#third-party-code-v4" target="_blank">`third-party-code-v4`</a>
 * 
 * Note: this is automatically generated.
 */
interface ThirdPartyCodeV4 {
    /**
     * Get third party code for a given summoner ID.
     */
    getThirdPartyCodeBySummonerId(region: Region, args?: object | Array<any>): String;
}

/**
 * TournamentStubV4 endpoints handle, accessed via `RiotApi.tournamentStubV4`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#tournament-stub-v4" target="_blank">`tournament-stub-v4`</a>
 * 
 * Note: this is automatically generated.
 */
interface TournamentStubV4 {
    /**
     * Create a mock tournament code for the given tournament.
     */
    createTournamentCode(region: Region, args?: object | Array<any>): Array<string>;
    /**
     * Gets a mock list of lobby events by tournament code.
     */
    getLobbyEventsByCode(region: Region, args?: object | Array<any>): tournamentStubV4.LobbyEventDTOWrapper;
    /**
     * Creates a mock tournament provider and returns its ID.
     * ## Implementation Notes
     * Providers will need to call this endpoint first to register their callback URL and their API key with the tournament system before any other tournament provider endpoints will work.
     */
    registerProviderData(region: Region, args?: object | Array<any>): int;
    /**
     * Creates a mock tournament and returns its ID.
     */
    registerTournament(region: Region, args?: object | Array<any>): int;
}

/**
 * TournamentV4 endpoints handle, accessed via `RiotApi.tournamentV4`.
 * # Riot Developer API Reference
 * <a href="https://developer.riotgames.com/apis#tournament-v4" target="_blank">`tournament-v4`</a>
 * 
 * Note: this is automatically generated.
 */
interface TournamentV4 {
    /**
     * Create a tournament code for the given tournament.
     */
    createTournamentCode(region: Region, args?: object | Array<any>): Array<string>;
    /**
     * Returns the tournament code DTO associated with a tournament code string.
     */
    getTournamentCode(region: Region, args?: object | Array<any>): tournamentV4.TournamentCodeDTO;
    /**
     * Update the pick type, map, spectator type, or allowed summoners for a code.
     */
    updateCode(region: Region, args?: object | Array<any>): void;
    /**
     * Gets a list of lobby events by tournament code.
     */
    getLobbyEventsByCode(region: Region, args?: object | Array<any>): tournamentV4.LobbyEventDTOWrapper;
    /**
     * Creates a tournament provider and returns its ID.
     * ## Implementation Notes
     * Providers will need to call this endpoint first to register their callback URL and their API key with the tournament system before any other tournament provider endpoints will work.
     */
    registerProviderData(region: Region, args?: object | Array<any>): int;
    /**
     * Creates a tournament and returns its ID.
     */
    registerTournament(region: Region, args?: object | Array<any>): int;
}

interface RiotApi {
    /**
     * Get all champion mastery entries sorted by number of champion points descending,
     */
    req(endpoint: "championMasteryV4", method: "getAllChampionMasteries", region: Region, args?: object | Array<any>): object;
    /**
     * Get a champion mastery by player ID and champion ID.
     */
    req(endpoint: "championMasteryV4", method: "getChampionMastery", region: Region, args?: object | Array<any>): object;
    /**
     * Get a player's total champion mastery score, which is the sum of individual champion mastery levels.
     */
    req(endpoint: "championMasteryV4", method: "getChampionMasteryScore", region: Region, args?: object | Array<any>): object;
    /**
     * Returns champion rotations, including free-to-play and low-level free-to-play rotations (REST)
     */
    req(endpoint: "championV3", method: "getChampionInfo", region: Region, args?: object | Array<any>): object;
    /**
     * Get players by summoner ID.
     * ## Implementation Notes
     * This endpoint returns a list of active Clash players for a given summoner ID. If a summoner registers for multiple tournaments at the same time (e.g., Saturday and Sunday) then both registrations would appear in this list.
     */
    req(endpoint: "clashV1", method: "getPlayersBySummoner", region: Region, args?: object | Array<any>): object;
    /**
     * Get team by ID.
     */
    req(endpoint: "clashV1", method: "getTeamById", region: Region, args?: object | Array<any>): object;
    /**
     * Get all active or upcoming tournaments.
     */
    req(endpoint: "clashV1", method: "getTournaments", region: Region, args?: object | Array<any>): object;
    /**
     * Get tournament by team ID.
     */
    req(endpoint: "clashV1", method: "getTournamentByTeam", region: Region, args?: object | Array<any>): object;
    /**
     * Get tournament by ID.
     */
    req(endpoint: "clashV1", method: "getTournamentById", region: Region, args?: object | Array<any>): object;
    /**
     * Get all the league entries.
     */
    req(endpoint: "leagueExpV4", method: "getLeagueEntries", region: Region, args?: object | Array<any>): object;
    /**
     * Get the challenger league for given queue.
     */
    req(endpoint: "leagueV4", method: "getChallengerLeague", region: Region, args?: object | Array<any>): object;
    /**
     * Get league entries in all queues for a given summoner ID.
     */
    req(endpoint: "leagueV4", method: "getLeagueEntriesForSummoner", region: Region, args?: object | Array<any>): object;
    /**
     * Get all the league entries.
     */
    req(endpoint: "leagueV4", method: "getLeagueEntries", region: Region, args?: object | Array<any>): object;
    /**
     * Get the grandmaster league of a specific queue.
     */
    req(endpoint: "leagueV4", method: "getGrandmasterLeague", region: Region, args?: object | Array<any>): object;
    /**
     * Get league with given ID, including inactive entries.
     */
    req(endpoint: "leagueV4", method: "getLeagueById", region: Region, args?: object | Array<any>): object;
    /**
     * Get the master league for given queue.
     */
    req(endpoint: "leagueV4", method: "getMasterLeague", region: Region, args?: object | Array<any>): object;
    /**
     * Get League of Legends status for the given shard.
     * ## Rate Limit Notes
     * Requests to this API are not counted against the application Rate Limits.
     */
    req(endpoint: "lolStatusV3", method: "getShardData", region: Region, args?: object | Array<any>): object;
    /**
     * Get the players in Master tier.
     */
    req(endpoint: "lorRankedV1", method: "getLeaderboards", region: Region, args?: object | Array<any>): object;
    /**
     * Get match IDs by tournament code.
     */
    req(endpoint: "matchV4", method: "getMatchIdsByTournamentCode", region: Region, args?: object | Array<any>): object;
    /**
     * Get match by match ID.
     */
    req(endpoint: "matchV4", method: "getMatch", region: Region, args?: object | Array<any>): object;
    /**
     * Get match by match ID and tournament code.
     */
    req(endpoint: "matchV4", method: "getMatchByTournamentCode", region: Region, args?: object | Array<any>): object;
    /**
     * Get matchlist for games played on given account ID and platform ID and filtered using given filter parameters, if any.
     * ## Implementation Notes
     * A number of optional parameters are provided for filtering. It is up to the caller to ensure that the combination of filter parameters provided is valid for the requested account, otherwise, no matches may be returned.
     * 
     * If beginIndex is specified, but not endIndex, then endIndex defaults to beginIndex+100. If endIndex is specified, but not beginIndex, then beginIndex defaults to 0. If both are specified, then endIndex must be greater than beginIndex. The maximum range allowed is 100, otherwise a 400 error code is returned.
     * 
     * If beginTime is specified, but not endTime, then endTime defaults to the the current unix timestamp in milliseconds (the maximum time range limitation is not observed in this specific case). If endTime is specified, but not beginTime, then beginTime defaults to the start of the account's match history returning a 400 due to the maximum time range limitation. If both are specified, then endTime should be greater than beginTime. The maximum time range allowed is one week, otherwise a 400 error code is returned.
     */
    req(endpoint: "matchV4", method: "getMatchlist", region: Region, args?: object | Array<any>): object;
    /**
     * Get match timeline by match ID.
     * ## Implementation Notes
     * Not all matches have timeline data.
     */
    req(endpoint: "matchV4", method: "getMatchTimeline", region: Region, args?: object | Array<any>): object;
    /**
     * Get current game information for the given summoner ID.
     */
    req(endpoint: "spectatorV4", method: "getCurrentGameInfoBySummoner", region: Region, args?: object | Array<any>): object;
    /**
     * Get list of featured games.
     */
    req(endpoint: "spectatorV4", method: "getFeaturedGames", region: Region, args?: object | Array<any>): object;
    /**
     * Get a summoner by account ID.
     */
    req(endpoint: "summonerV4", method: "getByAccountId", region: Region, args?: object | Array<any>): object;
    /**
     * Get a summoner by summoner name.
     */
    req(endpoint: "summonerV4", method: "getBySummonerName", region: Region, args?: object | Array<any>): object;
    /**
     * Get a summoner by PUUID.
     */
    req(endpoint: "summonerV4", method: "getByPUUID", region: Region, args?: object | Array<any>): object;
    /**
     * Get a summoner by summoner ID.
     */
    req(endpoint: "summonerV4", method: "getBySummonerId", region: Region, args?: object | Array<any>): object;
    /**
     * Get the challenger league.
     */
    req(endpoint: "tftLeagueV1", method: "getChallengerLeague", region: Region, args?: object | Array<any>): object;
    /**
     * Get league entries for a given summoner ID.
     */
    req(endpoint: "tftLeagueV1", method: "getLeagueEntriesForSummoner", region: Region, args?: object | Array<any>): object;
    /**
     * Get all the league entries.
     */
    req(endpoint: "tftLeagueV1", method: "getLeagueEntries", region: Region, args?: object | Array<any>): object;
    /**
     * Get the grandmaster league.
     */
    req(endpoint: "tftLeagueV1", method: "getGrandmasterLeague", region: Region, args?: object | Array<any>): object;
    /**
     * Get league with given ID, including inactive entries.
     */
    req(endpoint: "tftLeagueV1", method: "getLeagueById", region: Region, args?: object | Array<any>): object;
    /**
     * Get the master league.
     */
    req(endpoint: "tftLeagueV1", method: "getMasterLeague", region: Region, args?: object | Array<any>): object;
    /**
     * Get a list of match ids by PUUID.
     */
    req(endpoint: "tftMatchV1", method: "getMatchIdsByPUUID", region: Region, args?: object | Array<any>): object;
    /**
     * Get a match by match id.
     */
    req(endpoint: "tftMatchV1", method: "getMatch", region: Region, args?: object | Array<any>): object;
    /**
     * Get a summoner by account ID.
     */
    req(endpoint: "tftSummonerV1", method: "getByAccountId", region: Region, args?: object | Array<any>): object;
    /**
     * Get a summoner by summoner name.
     */
    req(endpoint: "tftSummonerV1", method: "getBySummonerName", region: Region, args?: object | Array<any>): object;
    /**
     * Get a summoner by PUUID.
     */
    req(endpoint: "tftSummonerV1", method: "getByPUUID", region: Region, args?: object | Array<any>): object;
    /**
     * Get a summoner by summoner ID.
     */
    req(endpoint: "tftSummonerV1", method: "getBySummonerId", region: Region, args?: object | Array<any>): object;
    /**
     * Get third party code for a given summoner ID.
     */
    req(endpoint: "thirdPartyCodeV4", method: "getThirdPartyCodeBySummonerId", region: Region, args?: object | Array<any>): object;
    /**
     * Create a mock tournament code for the given tournament.
     */
    req(endpoint: "tournamentStubV4", method: "createTournamentCode", region: Region, args?: object | Array<any>): object;
    /**
     * Gets a mock list of lobby events by tournament code.
     */
    req(endpoint: "tournamentStubV4", method: "getLobbyEventsByCode", region: Region, args?: object | Array<any>): object;
    /**
     * Creates a mock tournament provider and returns its ID.
     * ## Implementation Notes
     * Providers will need to call this endpoint first to register their callback URL and their API key with the tournament system before any other tournament provider endpoints will work.
     */
    req(endpoint: "tournamentStubV4", method: "registerProviderData", region: Region, args?: object | Array<any>): object;
    /**
     * Creates a mock tournament and returns its ID.
     */
    req(endpoint: "tournamentStubV4", method: "registerTournament", region: Region, args?: object | Array<any>): object;
    /**
     * Create a tournament code for the given tournament.
     */
    req(endpoint: "tournamentV4", method: "createTournamentCode", region: Region, args?: object | Array<any>): object;
    /**
     * Returns the tournament code DTO associated with a tournament code string.
     */
    req(endpoint: "tournamentV4", method: "getTournamentCode", region: Region, args?: object | Array<any>): object;
    /**
     * Update the pick type, map, spectator type, or allowed summoners for a code.
     */
    req(endpoint: "tournamentV4", method: "updateCode", region: Region, args?: object | Array<any>): object;
    /**
     * Gets a list of lobby events by tournament code.
     */
    req(endpoint: "tournamentV4", method: "getLobbyEventsByCode", region: Region, args?: object | Array<any>): object;
    /**
     * Creates a tournament provider and returns its ID.
     * ## Implementation Notes
     * Providers will need to call this endpoint first to register their callback URL and their API key with the tournament system before any other tournament provider endpoints will work.
     */
    req(endpoint: "tournamentV4", method: "registerProviderData", region: Region, args?: object | Array<any>): object;
    /**
     * Creates a tournament and returns its ID.
     */
    req(endpoint: "tournamentV4", method: "registerTournament", region: Region, args?: object | Array<any>): object;
}
